### ISSUE TITLE
ilmatieteenlaitos.py doesn't work

### ISSUE THREAD

**Issue by DoubleTom** [Meicceli/Sopel-modules#1]
15:00  User: .sää tampere
 15:00   Bot: Tampere Tampella - Auringonnousu tänään 8:46; Auringonlasku tänään 16:31; Päivän pituus on 7 h 45 min.

It's missing the temperature and other info.

**Comment by Meicceli** [comment]
Created a new version of the module which uses FMI's open api to get the weather information. They've changed their site so it now uses JS in displaying weather information on their site so it can no longer be parsed with BeautifulSoup.

You'll need an api key from https://ilmatieteenlaitos.fi/rekisteroityminen-avoimen-datan-kayttajaksi

**Comment by DoubleTom** [comment]
I have the API key. But it fails with following two messages related to their conditions. 

API key with quotes in the .py file.

Bot console:
Traceback (most recent call last):
  File "/home/sopel/sopel/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/sopel/.sopel/modules/ilmatieteenlaitos.py", line 154, in fmi
    bot.say(genFmiOutput(station, time, info) + paivan_pituus)
  File "/home/sopel/.sopel/modules/ilmatieteenlaitos.py", line 72, in genFmiOutput
    "3windDirection": (info[3], ""),
IndexError: list index out of range

in IRC
Bot:  IndexError: list index out of range (file "/home/sopel/.sopel/modules/ilmatieteenlaitos.py", line 72, in genFmiOutput)


API key without quotes in the .py file.

Bot console:
Error loading ilmatieteenlaitos: invalid syntax (ilmatieteenlaitos.py, line 18) (../<frozen importlib._bootstrap>:321)

**Comment by Meicceli** [comment]
Could you tell me with what command produced that error (I'd guess .sää <city>) ? I've used this module for quite a while (have been too lazy to upload it on github) with little problems.

**Comment by DoubleTom** [comment]
Oh sorry I forgot. It was: .sää tampere

raw log: (this comment thing lost some stuff)
http://pastebin.com/D8gtZEK9

**Comment by Meicceli** [comment]
Yeah I'm getting the same exact error with tampere. I'll look into it.

**Comment by Meicceli** [comment]
Problem was that some stations don't have all the data I'm looking to append to the output (not even null values for them...). Fixed this by appending missing null values manually.

**Comment by Meicceli** [comment]
Problem was that some stations don't have all the data I'm looking to append to the output (not even null values for them...). Fixed this by appending missing null values manually.
